import os
from celery import Celery
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
import datetime

# Create Celery instance (configuration happens in __init__.py)
celery_app = Celery('app_tasks', broker=os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0'))

@celery_app.task
def send_welcome_email(user_email, name):
    """
    Mock sending an async welcome email.
    In production, you'd use Flask-Mail or an API like SendGrid.
    """
    print(f"[BACKGROUND JOB] 🚀 Sending welcome email to {name} ({user_email})...")
    return True

@celery_app.task
def generate_monthly_statement(account_id, current_balance):
    """
    Generate PDF statement in background.
    """
    print(f"[BACKGROUND JOB] 📄 Generating PDF for Account {account_id}")
    
    # Ensure export directory exists
    export_dir = os.path.join(os.getcwd(), 'static', 'exports')
    os.makedirs(export_dir, exist_ok=True)
    
    filename = f"statement_acc_{account_id}_{datetime.datetime.now().strftime('%Y%m')}.pdf"
    filepath = os.path.join(export_dir, filename)
    
    c = canvas.Canvas(filepath, pagesize=letter)
    c.drawString(100, 750, f"Enterprise Banking Statement")
    c.drawString(100, 730, f"Account: {account_id}")
    c.drawString(100, 710, f"Date: {datetime.datetime.now().strftime('%B %Y')}")
    c.drawString(100, 690, f"Current Balance: ${current_balance}")
    c.drawString(100, 650, "Transaction History:")
    c.drawString(100, 630, "(Auto-generated by background task)")
    c.save()
    
    print(f"[BACKGROUND JOB] ✅ PDF saved to {filepath}")
    return filepath

@celery_app.task
def alert_fraud_suspicion(transaction_id):
    """Notify admins of suspected fraud"""
    print(f"🚨 [URGENT] Fraud suspected on Transaction {transaction_id}. Admins alerted.")
    return True
